### PR TITLE
rules: set uinput group to "input"

### PR DESCRIPTION
**Pull request by stacyharper**
fix: https://gitlab.alpinelinux.org/alpine/aports/-/issues/15240

### CODE REVIEW

**Comment by nekopsykose** [comment]
this means any user in the input group can keylog the system, that is why nobody can access uinput by default

**Comment by stacyharper** [comment]
> this means any user in the input group can keylog the system

Isn't this something accepted when giving the "input" group to some user?

> that is why nobody can access uinput by default

What are alternatives to this?

**Comment by stacyharper** [comment]
About keyloging, where do you read uinput is a way to keylog physical system inputs?

**Comment by bbonev** [comment]
I am wondering if `SUBSYSTEM=="misc"` should be `input` instead of `misc`

**Comment by bbonev** [comment]
According to the research I did, such type of rule is not included in systemd's udev. Also @nekopsykose have concerns about security and these look pretty valid. `eudev` have means for achieving this for a single user system by adding a custom rule file in `/etc`.

**Pull request closed without merging**
