### PR TITLE
Clear sysattr cache if a null pointer is passed

### PR DESCRIPTION
**Pull request by NaofumiHonda**
This solves #254

### CODE REVIEW

**Review by bbonev — APPROVED** [review]
LGTM, thanks!

**Comment by ArsenArsen** [comment]
the indentation here is a mix of spaces and tabs (set tabstop to 2 to see the effect).  what is it that requires this behavior?  I don't see it documented in systemd

**Comment by ArsenArsen** [comment]
oh, just saw the context.  lgtm if the indentation is fixed.

the code would likely benefit from a rebasing on top of upstream, or reforking

**Comment by NaofumiHonda** [comment]
Remove all tabs, but ...
I don't know the way for rebasing ...

**Comment by ArsenArsen** [comment]
that's out of scope for this PR - don't worry.  please squash the commits so that we don't have redundant commits.  LGTM

**Comment by bbonev** [comment]
@ArsenArsen you didn't click the review, I would assume it is good for a squashed merge, right?

**Comment by ArsenArsen** [comment]
right

**Pull request merged**
