### PR TITLE
Merge hwdb from systemd

### PR DESCRIPTION
**Pull request by bbonev**
All systemd's hwdb changes up to commit 5674b74c4f99e433fd8e7242e9f16f6ddfece94c

### CODE REVIEW

**Comment by lu-zero** [comment]
Looks like github added a spurious merge branch =/

**Comment by bbonev** [comment]
That wasn't github, I think that I did a rebase on the changes that I pushed without a PR

**Comment by ArsenArsen** [comment]
`rebase -i` + drop would solve that

**Comment by bbonev** [comment]
I had to force push after the rebase... This is an OUI database update from IEEE, should be safe to merge

**Review by ArsenArsen — APPROVED** [review]
lgtm

**Pull request merged**
